-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 20:45:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WIFIProbeAnalysis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WIFIProbeAnalysis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WIFIProbeAnalysis` DEFAULT CHARACTER SET utf8 ;
USE `WIFIProbeAnalysis` ;

-- -----------------------------------------------------
-- Table `WIFIProbeAnalysis`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WIFIProbeAnalysis`.`task` (
  `task_id` INT(40) NOT NULL,
  `task_name` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `start_time` DATETIME NULL,
  `finish_time` DATETIME NULL,
  `task_type` VARCHAR(10) NULL,
  `task_status` VARCHAR(10) NULL,
  `task_param` VARCHAR(150) NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WIFIProbeAnalysis`.`user_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WIFIProbeAnalysis`.`user_visit` (
  `shop_id` INT NOT NULL,
  `mmac` VARCHAR(18) NOT NULL,
  `time` DATETIME NOT NULL,
  `total_flow` INT NULL,
  `check_in_flow` INT NULL,
  `check_in_rate` DOUBLE NULL,
  `shallow_visit_rate` DOUBLE NULL,
  `deep_visit_rate` DOUBLE NULL,
  PRIMARY KEY (`shop_id`, `mmac`, `time`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WIFIProbeAnalysis`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WIFIProbeAnalysis`.`user` (
  `mac` VARCHAR(18) NOT NULL,
  `brand` VARCHAR(32) NULL,
  `first_visit_time` DATETIME NULL,
  `last_visit_time` DATETIME NULL,
  `new_visit_time` VARCHAR(45) NULL,
  `activity_degree` VARCHAR(10) NULL,
  PRIMARY KEY (`mac`));


-- -----------------------------------------------------
-- Table `WIFIProbeAnalysis`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WIFIProbeAnalysis`.`shop` (
  `shop_id` INT NOT NULL,
  `mmac` VARCHAR(18) NOT NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  `addr` VARCHAR(100) NULL,
  PRIMARY KEY (`shop_id`, `mmac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WIFIProbeAnalysis`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WIFIProbeAnalysis`.`property` (
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `visit_cycle` VARCHAR(12) NULL,
  `visit_range` DOUBLE NULL,
  `visit_rssi` INT NULL,
  `activity_degree` VARCHAR(55) NULL,
  `visit_time_split` VARCHAR(45) NULL,
  `property_type` INT(1) NULL,
  PRIMARY KEY (`property_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WIFIProbeAnalysis`.`vendor_macs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WIFIProbeAnalysis`.`vendor_macs` (
  `mac_prefix` VARCHAR(18) NOT NULL,
  `vendor_name` VARCHAR(255) NULL,
  PRIMARY KEY (`mac_prefix`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
